[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'cd backend && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level info app:app'
