services:
  - type: web
    name: krishimitra-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: Gemini_API_key
        sync: false
      - key: Weather_API_key
        sync: false
      - key: GEMINI_MODEL
        value: gemini-pro
